title: Charles Zhang
description: 
author: "Charles Zhang"

theme: minima

plugins: 
 - jekyll-seo-tag
 
base_url: /

# Minima social links
twitter_username: chrlszhng
github_username: charles-zhng
linkedin_username: chrls-zhng

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/research.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md